

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
