version: '3.8'  # Recommended version

services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile  # 👈 Specify the correct path
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["node", "src/server.js"]

  worker:
    build:
      context: .
      dockerfile: src/Dockerfile  # 👈 Specify the correct path
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app
    command: ["node", "src/worker.js"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
