

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["node", "src/server.js"]

  worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["node", "src/worker.js"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
