

services:
  backend:
    build:
      context: ./backend  # 👈 Point to the backend folder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    command: ["node", "src/server.js"]

  worker:
    build:
      context: ./backend  # 👈 Same backend folder
      dockerfile: Dockerfile
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
    command: ["node", "src/worker.js"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
