version: "3.8"

services:
  backend:
    build:
      context: ./backend   # 👈 Point to backend folder
      dockerfile: Dockerfile   # 👈 Picks up Dockerfile inside backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Auto-reload on changes
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
